spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: 192.168.1.150
    port: 5672
    username: wuwei
    password: wuwei

  username: test
  password: testpassword